### ISSUE TITLE
[Bug] ccService.initializing, ccService.initialized and ccService.initializationError does not exist on NgcCookieConsentService

### ISSUE THREAD

**Issue by henning410** [tinesoft/ngx-cookieconsent#122]
### Ngx-CookieConsent Version

2.2.3

### CookieConsent Version

3.1.1

### Angular CLI (or Nx CLI) Version

12.2.14

### Node Version

16.13.0

### OS Version

Windows

### Expected Behaviour

As mentioned in the README, the methods `ccService.initializing`, `ccService.initialized` and `ccService.initializationError` called on NgcCookieConsentService should work in ngOnInit()

I need these methods to call a function when user allow cookies.

### Actual Behaviour

TS2339: Property initializationError$ does not exist on type NgcCookieConsentService.
TS2551: Property initialized$ does not exist on type NgcCookieConsentService. Did you mean initialize? 
TS2551: Property initializing$ does not exist on type NgcCookieConsentService. Did you mean initialize?

### Steps to reproduce the behaviour

1. setup same angular cli
2. copy code from README

**Comment by Bhorga** [comment]
did this issue got resolved? any steps to solve this issue?

**Comment by tinesoft** [comment]
Please feel free to re-open, with repro project if still revelant
