### ISSUE TITLE
[Bug] Wrong `peerDependencies` for rxjs for Angular v14+

### ISSUE THREAD

**Issue by BeratS** [tinesoft/ngx-cookieconsent#126]
### Ngx-CookieConsent Version

4.0.0

### CookieConsent Version

3.1.1

### Angular CLI (or Nx CLI) Version

14

### Node Version

16

### OS Version

Windows

### Expected Behaviour

peer rxjs@"~6.6.0" from ngx-cookieconsent@4.0.0

The angular 14 it uses "rxjs": "~7.5.0",

I am not able to install other libraries - so I must use --force

### Actual Behaviour

peer rxjs@"~6.6.0" from ngx-cookieconsent@4.0.0

The angular 14 it uses "rxjs": "~7.5.0",

I am not able to install other libraries - so I must use --force

### Steps to reproduce the behaviour

peer rxjs@"~6.6.0" from ngx-cookieconsent@4.0.0

The angular 14 it uses "rxjs": "~7.5.0",

I am not able to install other libraries - so I must use --force

**Comment by tinesoft** [comment]
Fixed in https://github.com/tinesoft/ngx-cookieconsent/releases/tag/v4.0.1

**Comment by BeratS** [comment]
Thanks a lot @tinesoft

**Comment by miguel-fulfil** [comment]
> Fixed in https://github.com/tinesoft/ngx-cookieconsent/releases/tag/v4.0.1

@tinesoft this still causes a dependency conflict. We're on 14.2.7 with ionic and have been using rxjs 6.6.7 successfully. Migrating to rxjs 7 is not a requirement of `@angular/core` nor `@angular/common` - have to use `ngx-cookieconsent@4.0.0`
https://github.com/angular/angular/blob/main/packages/core/package.json#L19
https://github.com/angular/angular/blob/main/packages/common/package.json#L24
