### ISSUE TITLE
Correct configuration delivery (translations)

### ISSUE THREAD

**Issue by magoss** [tinesoft/ngx-cookieconsent#14]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### OS and Version?
Windows 10

### Versions
Angular 4.2.4

### Desired functionality
I use translation service inside my Angular app. I have a problem with delivery of translations to ngx-cookieconsent configuration. Is there any way to pass configuration object later, inside component? I see it's required to initialize module, but It's odd to pass translation from the module level. I mean:

NgcCookieConsentModule.forRoot(cookieConfig)

I have to have translations already here, but I have it only in a component - they come from a service.

Would be awesome to abstract out messages from configuration object to make it translateable.

**Comment by tinesoft** [comment]
Hi @magoss ,

This would be indeed a great feature. I will start working on it asap.
Quick question: what translation library do you use? [ngx-translate](https://github.com/ngx-translate/core)?

**Comment by magoss** [comment]
Yup, ngx-translate.

**Comment by yduartep** [comment]
This could be a great feature. I have to do something like this to allow translations before to open it...

combineLatest(
        this.translate.get('cookie.content'),
        this.translate.get('cookie.button'),
        this.translate.get('cookie.link')
      ).subscribe(data => {
        this.cookieConfig.content.message = data[0];
        this.cookieConfig.content.dismiss = data[1];
        this.cookieConfig.content.deny = data[2];

        this.ccService.init(this.cookieConfig);
        this.ccService.open();
      });
