### ISSUE TITLE
It's not possible to close completely the Cookie Policy once answered

### ISSUE THREAD

**Issue by yduartep** [tinesoft/ngx-cookieconsent#15]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions

Angular CLI: 6.0.0
Node: 10.0.0
OS: darwin x64
Angular: 6.0.0

### Desired functionality

In this moment once you answer the consent, the popup closes but an small tab with the title "Cookie Policy" is left. I need to close everything once is answered but there isn't a close method.

**Comment by tinesoft** [comment]
Hi @yduartep 

Sorry for the late answer, 'been a bit busy lately...

To achieve what you want, you can call  `CookieConsentService.toggleRevokeButton(false)`
in the callback to "close event" as such:
```
this.popupCloseSubscription = this.ccService.popupClose$.subscribe( () => {

       this.ccService.toggleRevokeButton(false);
      });
```

Later, after i will add the missing `CookieConsentService.close(showRevoke:boolean)` method,
which does some additional checks + animations, before hiding the "Cookie Policy" element.

Then you can just replace `toggleRevokeButton(show:boolean)` with that method instead.

**Comment by cyberiumchain** [comment]
use destroy in if block or something to check if consent is acquired or whatever your case is. I used this method to hide it in browser.
