### ISSUE TITLE
NgcHTMLElements won't be updated

### ISSUE THREAD

**Issue by SebastianRuecker** [tinesoft/ngx-cookieconsent#16]
### Bug Report
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.0.8
Node: 10.5.0
OS: darwin x64
Angular: 6.0.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3
```

### Report
if i try to change for example the link-element (remove of the target-element) 
`<a aria-label="learn more about cookies" class="cc-link" href="{{href}}">{{link}}</a>`
the configuration is updated as desired but the output is still the same
`<a aria-label="learn more about cookies" class="cc-link" href="{{href}}" target="_blank">{{link}}</a>`

How can this be achieved?

**Comment by tinesoft** [comment]
Hi

Can you show your code?
Did you call `cookieConsentService.init(newConfig)` after you changed the `linked-element`

**Comment by SebastianRuecker** [comment]
Hi

this is my code...
```
public openCookieConsent(data: CampaignFrontEndDto) {
        const currentConfig = this._ccService.getConfig();
        ...
        const elements = new NgcHTMLElements();
        elements.link = '<a aria-label="learn more about cookies" class="cc-link" href="{{href}}">{{link}}</a>';
        currentConfig.elements = elements;

        this._ccService.destroy();

        this._ccService.init(currentConfig);

        this._ccService.open();
    }
```

The output of currentConfig is as expected with the updated values (by console.log(...);)...
but the output is as before (with the target = "_ blank") ... :-(

**Comment by SebastianRuecker** [comment]
any suggestions or approaches?

**Comment by tinesoft** [comment]
Hi @SebastianRuecker 

Sorry, i didn't have time to investigate on your issue :), i've been a bit busy lately...
Your code seems correct to me though.
I will have a closer  look tonight and let you know asap.


Cheers

**Comment by tinesoft** [comment]
Okay, 

i did some investigating, and i have a solution for you :)
The problem you mentioned is explained on the issue tracker of `cookieconsent` 
 itself (which is used by `ngx-cookieconsent` underneath): https://github.com/insites/cookieconsent/issues/169#issuecomment-392508863

Actually, the property of `NgcHTMLElements` that you need to change is **messagelink** (not **link**).
