### ISSUE TITLE
initialize$ stream never called

### ISSUE THREAD

**Issue by IH8Github** [tinesoft/ngx-cookieconsent#19]
### Bug Report

The initialize$ stream is never called. I think this is coming from the init method in NgcCookieConsentService declaring this.config.onInitialize whereas the callback hook in cookieconsent.js is onInitialise (with an 's' not a 'z'). I fixed this locally and the callback seems to be working correctly now.

**Comment by tinesoft** [comment]
Good catch! 
will be released soon (in v1.1.1)
