### ISSUE TITLE
Error: Cannot find name 'NgcInitializeEvent' and 'NgcStatusChangeEvent' AND  Cannot read property 'initialise' of undefined

### ISSUE THREAD

**Issue by Byloor** [tinesoft/ngx-cookieconsent#2]
Hi,

I would like to  use ngx-cookie consent package in my angular 4 application(built with angular cli) . I do not have a systemjs file. Hence except that part , I followed each step as in the documentation . I am having 4 error messages
two errors with following message
1.  Cannot read property 'initialise' of undefined
    at NgcCookieConsentService.init (cookieconsent.service.js:53)
    at new NgcCookieConsentService (cookieconsent.service.js:23)
    at _createClass (core.es5.js:9532)
    at _createProviderInstance$1 (core.es5.js:9500)
    at resolveNgModuleDep (core.es5.js:9485)
    at NgModuleRef_.get (core.es5.js:10577)
    at resolveDep (core.es5.js:11080)
    at createClass (core.es5.js:10933)
    at createDirectiveInstance (core.es5.js:10764)
    at createViewNodes (core.es5.js:12212)

2. Cannot find name 'NgcInitializeEvent'.
 Cannot find name 'NgcStatusChangeEvent'.

Please help.

**Comment by tinesoft** [comment]
Hi @Byloor 

Please for your future issues, provide the minimum info mentioned in the issue template (when creating it): angular-cli version, repro steps (which command of angular-cli produces the error,..) etc. This helps me help you faster!

Concerning your error 1 , it almost like it could not found cookieconsent.js library. Please try this:
* `rm -rf node_modules` (to be safe)
* `npm i  --save cookieconsent`
* `npm i  --save ngx-cookieconsent`
* edit `.angular-cli.json`: 
```
"scripts": [
        "../node_modules/cookieconsent/build/cookieconsent.min.js"
      ],

      "styles": [
        "../node_modules/cookieconsent/build/cookieconsent.min.css"
      ],
```
* ng serve

**Comment by Byloor** [comment]
@tinesoft 
Thank you , It works! I dont know what was wrong thou, the only thing i hadn't run was 

- rm -rf node_modules

And for the second error : i added 
 import { NgcInitializeEvent , NgcStatusChangeEvent } from 'ngx-cookieconsent';
in the app.component.ts file. and it was resolved!

**Comment by tinesoft** [comment]
I suspect the dependencies have not been installed correctly the  1st time.
Sometime a  simple `rm -rf node_modules`  can help solving many issues with node  packages! :smile:

**Comment by Byloor** [comment]
Sorry, I have another issue. Not sure,if it has been resolved already. Clicking on "GOT IT" button hides the banner. But it re-appears if i load again . Is there a time period I have to mention. And my browser does save cookies( I verified)

**Comment by mastermind3043** [comment]
I faced issue #1 because I'd skipped the dependency for insites' js
