### ISSUE TITLE
Cannot find name NgIntitializeEvent and NgcStatusChangeEvent   

### ISSUE THREAD

**Issue by Byloor** [tinesoft/ngx-cookieconsent#3]
continued with https://github.com/tinesoft/ngx-cookieconsent/issues/2  -was not resolved completely. Hence opening the issue again . Please help :)

**Comment by tinesoft** [comment]
Hi @Byloor 

There is indeed an issue with those 2 intefarces,  not being not exported  in the distributed library as they should. I'm working on a fix, and will release a patch version soon.

Stay tuned!

**Comment by Byloor** [comment]
@tinesoft I look forward to it ! :)

**Comment by tinesoft** [comment]
Hi @Byloor 

Sorry for the delay.

Regarding your issue, and contrary to my previous remark, the `NgIntitializeEvent` and `NgcStatusChangeEvent` _were_ actually exported as they were supposed to...
and you _do need_ to import  from 'ngx-cookieconsent', if you want to use them in your code.

But there is indeed an issue with the cookie  status not being persited when clicking 'Got It'.
I'm closing this one, and creating #4 to track that issue.

**Comment by Byloor** [comment]
saw your response in [https://stackoverflow.com/questions/46583242/ngx-cookieconsent-cannot-find-name-ngcinitializeevent-and-ngcstatuschangeev/46763697#46763697](url) .Is the issue resolved?
