### ISSUE TITLE
Manage cookies of multiple domains in one application

### ISSUE THREAD

**Issue by sylvainonweb** [tinesoft/ngx-cookieconsent#36]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### CookieConsent and Library Versions?
```
- cookieconsent version: 3.1.0
- ngx-cookieconsent version: ^2.0.0
```

### OS Version?
CentOS 7.6.1810

### Angular, Node and al Versions?
Angular CLI: 7.0.5
Node: 9.11.1
OS: win32 x64
Angular: 7.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.5
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.0.5
@angular-devkit/schematics        7.0.5
@angular/cdk                      7.0.4
@angular/cli                      7.0.5
@angular/material                 7.0.4
@angular/platform-server          7.0.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.0.5
@schematics/update                0.10.5
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1

### Repro steps

NA

### The log given by the failure

NA

### Desired functionality

Be able to set the NgcCookieConsentConfig.cookieDomain property to multiple domains.
In my case, multiple domains are managed by the same angular application

**Comment by tinesoft** [comment]
Hi @sylvainonweb ,

I'm not sure that i understand what you mean when you say: 

> In my case, multiple domains are managed by the same angular application

Is it, that the same angular app is running (installed) from different domains? Like:

- domain1.mycompany.com
- domain2.mycompany.com
- ...

In that case, what don't you set the `cookie.domain` **dynamically**, by retrieving the domain via a `window.location.hostname` for example?

**Comment by sylvainonweb** [comment]
Yes, it will do this. Thanks
