### ISSUE TITLE
Update npm version of your project

### ISSUE THREAD

**Issue by sylvainonweb** [tinesoft/ngx-cookieconsent#37]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
```

### CookieConsent and Library Versions?
```
- cookieconsent version: 3.1.0
- ngx-cookieconsent version: 2.0.0
```

### OS Version?

Windows 10

### Angular, Node and al Versions?

Angular CLI: 7.0.5
Node: 9.11.1
OS: win32 x64
Angular: 7.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.5
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.0.5
@angular-devkit/schematics        7.0.5
@angular/cdk                      7.0.4
@angular/cli                      7.0.5
@angular/material                 7.0.4
@angular/platform-server          7.0.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.0.5
@schematics/update                0.10.5
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1

### Desired functionality

Could you update npm version of your project?
Actually, github is in 2.1.0 version but npm is in 2.0.0

**Comment by tinesoft** [comment]
Hi @sylvainonweb 

Good catch! I don't know what happened, but it should be fixed now with release of [v2.1.1](https://github.com/tinesoft/ngx-cookieconsent/releases/tag/v2.1.1)


Cheers!
