### ISSUE TITLE
Cookie Status not persisted when clicking 'Got It'

### ISSUE THREAD

**Issue by tinesoft** [tinesoft/ngx-cookieconsent#4]

**Comment by tinesoft** [comment]
Ok, turns out you **must** to set the `cookie.domain` option from the config object `NgcCookieConfig` (even in localhost) for the cookie to be set.

I have updated docs and code, to make that more clear for future users.

In the meantime, simply set this parameter in your consuming app and you should be good to go!

```ts
import {NgcCookieConsentModule, NgcCookieConsentConfig} from 'ngx-cookieconsent';

const cookieConfig:NgcCookieConsentConfig = {
  cookie: {
    domain: 'your.domain.com' // it is mandatory to set a domain (even in localhost), for cookies to work properly
  }
};

@NgModule({
  declarations: [AppComponent, ...],
  imports: [NgcCookieConsentModule.forRoot(cookieConfig), ...],  
  bootstrap: [AppComponent]
})
export class AppModule {
}
```

**Note:** if you are using Angular CLI for your consuming app, you can take advantage of [environments](https://github.com/angular/angular-cli/wiki/stories-application-environments) to define different domains based on your running environment:

*environments/environment.ts:* (dev)
```
export const environment = {
  production: false,
  cookieDomain: 'localhost' // -<< must be 'localhost'
};
```

*environments/environment.prod.ts:* (prod)
```
export const environment = {
  production: true,
  cookieDomain: 'your.domain.com' // -<< must be the domain of deployed app
};
```

and use it as such:

```ts
import {NgcCookieConsentModule, NgcCookieConsentConfig} from 'ngx-cookieconsent';
import { environment } from './../environments/environment';

const cookieConfig:NgcCookieConsentConfig = {
  cookie: {
    domain: environment.domain // -<< domain will change base on your running env
  }
};

@NgModule({
  declarations: [AppComponent, ...],
  imports: [NgcCookieConsentModule.forRoot(cookieConfig), ...],  
  bootstrap: [AppComponent]
})
export class AppModule {
}
```

**Comment by Byloor** [comment]
Works Perfectly. i had set cookie.domain before(even though it was mentioned as not mandatory) . I had set it to http://localhost:4200/  . 
Thank you so much :)

**Comment by tinesoft** [comment]
Good to know!

FYI, you don't need the full URL, just the domain name (`localhost` or `my.domain.com`) is enough. [See](https://www.mxsasha.eu/blog/2014/03/04/definitive-guide-to-cookie-domains/)

It wasn't clear to me either that this setting was kind of **mandatory** (and not just` "recommended"` as stated in [official docs).](https://github.com/insites/cookieconsent/blob/master/src/cookieconsent.js#L183) 
Anyway, i will update the code to enforce that and update docs to make that more clear in the future.

**Comment by habibmohamed06** [comment]
I think the best way to avoid this kind of problem is to look for the domain name directly :
const cookieConfig:NgcCookieConsentConfig = {
  cookie: {
    domain: window.location.hostname 
  }
};
