### ISSUE TITLE
How to dynamic set domain to current one

### ISSUE THREAD

**Issue by GetTaxSolutions** [tinesoft/ngx-cookieconsent#41]
Hello, I'm trying to set the domain property to using the current origin domain in app.module.
How can I do it?
I have this definition in imports and when try to set the domain using function or expression the compiler throw exception that is not possible. If I using window.local.domain the SSR throw exception that can't resolve window object. Is it possible to pass some provider which will set the domain?
  
NgcCookieConsentModule.forRoot(
      {
      'cookie': {
        'domain': getCurrentDomain()
      },
      'palette': {
        'popup': {
          'background': '#efefef',
            'text': '#404040'
        },
        'button': {
          'background': '#8ec760',
            'text': '#ffffff'
        }
      },
      'theme': 'classic', 
      'position': 'bottom-right'
    }),

**Comment by Martin-Andersen** [comment]
use this code https://stackoverflow.com/questions/46583242/ngx-cookieconsent-cannot-find-name-ngcinitializeevent-and-ngcstatuschangeev

**Comment by ADringer** [comment]
Hi, I'm have the same question and don't believe the question has been answered.

We have 'pop-up' environments which have random names and so can't put the site name into the environment file. I've been looking at how to dynamically set the cookieDomain property but can't work out how to do this as it's expecting a value. Is it possible to give it a callback function or something to get this information?

**Comment by ADringer** [comment]
I've found out how to do this:

So configure the module using a a dummy domain (using the example above):

```
NgcCookieConsentModule.forRoot(
{
'cookie': {
'domain': 'not-set'
},
'palette': {
'popup': {
'background': '#efefef',
'text': '#404040'
},
'button': {
'background': '#8ec760',
'text': '#ffffff'
}
},
'theme': 'classic',
'position': 'bottom-right'
}),
```

Then create a function that takes in the `NgcCookieConsentConfig` object (and any other objects you need):

```
export function cookieConfigFactory(http: HttpClient, config: NgcCookieConsentConfig,) {
  return () => config.cookie.domain = 'set the domain here';
}
```

And then in the AppModule providers list add:

```
{
      provide: APP_INITIALIZER,
      useFactory: cookieConfigFactory,
      deps: [HttpClient, NgcCookieConsentConfig],
      multi: true
    }
```

From what I understand (although might be wrong), using forRoot() on the module makes the `NgcCookieConsentConfig` a singleton so we can inject it into our function and it will be the same one used as the module.

Adding the `APP_INITIALIZER' makes the function run (and update the domain) before it bootstraps the modules, so the domain will be updated before being used.

**Comment by tinesoft** [comment]
Closing the issue, as @ADringer solution did the trick!

**Comment by VirendraMaheta7** [comment]
Hey there! 
I need to show cookie consent on www.xyz.com
But I need to hide that on www.xyz.com/admin, Is it possible?

**Comment by DouglasLapsley** [comment]
Also a solution: cookie: { domain: window.location.hostname, },
