### ISSUE TITLE
Is it possible to include multiple links and insert them in the middle of a sentence? 

### ISSUE THREAD

**Issue by DaYuClo** [tinesoft/ngx-cookieconsent#43]
I searched through the documentation but cannot find the answers to the following questions.

Question 1: Is it possible to have more than one links?

Question 2: Is it possible to insert the link in the middle of a sentence instead of at the end by default? 

Default:
> This website use cookies to ensure you get the best experience on our website. [Privacy Policy](url)

What I want:

> By using our site, you acknowledge that you have read and understand our [Cookie Policy](url), [Privacy Policy](url), and our [Terms of Service](url).

Is it possible?

Thank you.

**Comment by tinesoft** [comment]
Hi @DaYuClo 

> Question 1: Is it possible to have more than one links

> Question 2: Is it possible to insert the link in the middle of a sentence instead of at the end by default?


Yes, you can totally customize the appearance of the cookie bar as you which.

I have added a new section in the [README](https://github.com/tinesoft/ngx-cookieconsent/tree/master#custom-layout-support) to describe how this can be achieved.
Plus, i have [softened some types definitions](https://github.com/tinesoft/ngx-cookieconsent/commit/4b32ce0b253afafd09888e97b9b929fcb6e49774) to avoid typescript compilation errors when defining custom properties. Please update to [v2.2.0](https://github.com/tinesoft/ngx-cookieconsent/releases/tag/v2.2.0)


Then in your case, the following configuration can be used to achieve what you described:

```
import {NgcCookieConsentModule, NgcCookieConsentConfig} from 'ngx-cookieconsent';

const cookieConfig:NgcCookieConsentConfig = {
  cookie: {
    domain: 'localhost'// it is recommended to set your domain, for cookies to work properly
  },
  palette: {
    popup: {
      background: '#000'
    },
    button: {
      background: '#f1d600'
    }
  },
  theme: 'edgeless',
  type: 'opt-out',
  layout: 'my-custom-layout',
  layouts: {
    "my-custom-layout": '{{messageLink}}{{compliance}}'
  },
  elements:{
    messageLink: `
    <span id="cookieconsent:desc" class="cc-message">{{message}} 
      <a aria-label="learn more about cookies" tabindex="0" class="cc-link" href="{{cookiePolicyHref}}" target="_blank">{{cookiePolicyLink}}</a>, 
      <a aria-label="learn more about our privacy policy" tabindex="1" class="cc-link" href="{{privacyPolicyHref}}" target="_blank">{{privacyPolicyLink}}</a> and our 
      <a aria-label="learn more about our terms of service" tabindex="2" class="cc-link" href="{{tosHref}}" target="_blank">{{tosLink}}</a>
    </span>
    `,
  },
  content:{
    message: 'By using our site, you acknowledge that you have read and understand our ',
    
    cookiePolicyLink: 'Cookie Policy',
    cookiePolicyHref: 'https://cookie.com',

    privacyPolicyLink: 'Privacy Policy',
    privacyPolicyHref: 'https://privacy.com',

    tosLink: 'Terms of Service',
    tosHref: 'https://tos.com',
  }
};


@NgModule({
  declarations: [AppComponent, ...],
  imports: [NgcCookieConsentModule.forRoot(cookieConfig), ...],  
  bootstrap: [AppComponent]
})
export class AppModule {
}

```

**Comment by DaYuClo** [comment]
@tinesoft I really appreciate your work and help.  Kudo!
