### ISSUE TITLE
accessibilty updates

### ISSUE THREAD

**Issue by liyokuna** [tinesoft/ngx-cookieconsent#46]
Hello Guys,

I am using you package for an accessibility [project](http://ng-boosted.orange.com/#/home). A colleague run accessibility tests and shared through this [issue ](https://github.com/Orange-OpenSource/Orange-Boosted-Angular/issues/18#issuecomment-484891525)and change updates to be made to improve the pop up window.
I am trying to run ngx-cookieconsent to do a PR soon.
```
- [* ] feature request:
-> removing aria-label="cookieconsent" from the div (aria-labelledby is enough)
-> using real buttons instead of a a html tag with role set to button
-> No need of aria-label in these links because text links are understandables, but if you want to use aria-label translate them. let the user to input translate inside aria-label.
-> put the text of the popup and the links inside a tag ( p or div html tag)
```
Before starting any changes are you interesting by this feedback ?

### CookieConsent and Library Versions?
```
- cookieconsent version: 3.1.0
- ngx-cookieconsent version: 2.0.0
```

B.R

**Comment by tinesoft** [comment]
Hi @liyokuna 

Thanks for your feedback regarding  accessibility.  But i'm afraid that they must be directed to [cookieconsent](https://github.com/insites/cookieconsent) project instead. This library simply provides the integration with Angular, but the heavy work is done by `cookieconsent`.

Cheers!

**Comment by liyokuna** [comment]
yeah I just realized that by going through your code, my bad.
thanks.
