### ISSUE TITLE
Stackblitz demo does not work

### ISSUE THREAD

**Issue by mightymatth** [tinesoft/ngx-cookieconsent#69]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report 
- [ ] feature request
```

---

In master branch (commit `43717bc`):
https://stackblitz.com/github/tinesoft/ngx-cookieconsent/tree/master/demo
or
https://stackblitz.com/github/tinesoft/ngx-cookieconsent/tree/43717bc/demo

After opening, it asks to install missing packages (@nguniversal/commonngx-cookieconsent@angularclass/hmr). After installing, nothing happens, but there is an error in console:

```bash
ERROR TypeError: Cannot read property 'initialise' of undefined
    at NgcCookieConsentService.init (cookieconsent.service.ts:162)
    at new NgcCookieConsentService (cookieconsent.service.ts:119)
    at _createClass (ng_module.ts:176)
    at _createProviderInstance (ng_module.ts:144)
    at resolveNgModuleDep (ng_module.ts:106)
    at NgModuleRef_.get (refs.ts:507)
    at resolveDep (provider.ts:423)
    at createClass (provider.ts:283)
    at createDirectiveInstance (provider.ts:136)
    at createViewNodes (view.ts:303)
```

**Comment by lorenzonet** [comment]
I've just set up the component in my application and I got the same error.
Angular 8.2.10
Angular/material 8.2.3

**Comment by adrienguyot** [comment]
same problem here

**Comment by tinesoft** [comment]
It looks like [Stackblitz does not support global scripts in the angular-cli.json](https://github.com/stackblitz/core/issues/407)... So the dependency `cookieconsent` is no loaded, thus the undefined error.

A workaround would be to manually add this script in the `head` section of the index.html
```
...
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/ngx-cookieconsent@2.2.3/bundles/ngx-cookieconsent.umd.js"></script>
...
```

but this is not working either at the moment😐...
