### ISSUE TITLE
Demo site cannot be run locally

### ISSUE THREAD

**Issue by mightymatth** [tinesoft/ngx-cookieconsent#70]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### OS Version?

> macOS Mojave

### Angular, Node and al Versions?

Angular CLI: 7.3.8
Node: 10.15.0
OS: darwin x64
Angular: 7.2.14

### Repro steps

After I've cloned the repo, installed dependencies (`npm install`), built demo app (`npm run demo`) and run demo app (`cd demo/dist && ngserve`), it fails with error.

### The log given by the failure

```bash
ERROR in /Users/mightymatth/.nvm/versions/node/v10.15.0/lib/node_modules/ngx-cookieconsent/esm5/ngx-cookieconsent.es5.js
Module not found: Error: Can't resolve 'rxjs' in '/Users/mightymatth/.nvm/versions/node/v10.15.0/lib/node_modules/ngx-cookieconsent/esm5'
```

### Desired functionality

It should successfully serve demo application.

**Comment by tinesoft** [comment]
Hi @mightymatth ,

Sorry for the late answer, I've been .
To run the demo app locally, the right command is: `gulp serve:demo` (from root folder) or `ng serve` (from `demo/` folder after having `npm install` dependencies).

What is inside `demo/dist` is not meant to be "ng" serve.

**Comment by tinesoft** [comment]
Hi @mightymatth ,

Sorry for the late answer, I've been .
To run the demo app locally, the right command is: `gulp serve:demo` (from root folder) or `ng serve` (from `demo/` folder after having `npm install` dependencies).

What is inside `demo/dist` is not meant to be "ng" serve.

**Comment by tinesoft** [comment]
Also,

Make sure to run `gulp link` (needed only once) to have the library available locally (required when running the demo locally).

I'm closing for now, feel free to re-open
