### ISSUE TITLE
Not able to initialize the popup.

### ISSUE THREAD

**Issue by Navin-vis** [tinesoft/ngx-cookieconsent#73]
![kaffenopopup](https://user-images.githubusercontent.com/58224142/71827963-61767600-30c7-11ea-8ed3-1737dab796aa.jpg)
Hi,
Please find the attachment and suggest me where i am going wrong.

**Comment by tinesoft** [comment]
Hi,

Please provide the minimun information, as listed in the [ISSUE_TEMPLATE](https://github.com/tinesoft/ngx-cookieconsent/blob/master/.github/ISSUE_TEMPLATE.md).
This helps reproducing, understanding and fixing the issue quicker.

Thanks

**Comment by Navin-vis** [comment]
Hi
Thanks for your response. But i solved the issue, i declare wrong css and js in angular.json file.
now i am closing the issue.
Thanks again.
