### ISSUE TITLE
ngx-cookieconsent@1.0.0 requires a peer of @angular/core@^2.0.0 but none is installed. You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by acuntex** [tinesoft/ngx-cookieconsent#8]
At the moment npm shows a warning when using ngx-cookieonsent with the latest angular version (5.0.0, previously 4.x).

> npm WARN ngx-cookieconsent@1.0.0 requires a peer of @angular/common@^2.0.0 but none is installed. You must install peer dependencies yourself.

Any chance this can be fixed?

**Comment by tinesoft** [comment]
Hi @acuntex 

ngx-cookieconsent@1.0.0 has **peerDependencies** on `@angular/core|common@^2.0.0`, which mean any version of angular from **2.x.x** to **latest** (installed as **dependencies** of your consuming app), should work just fine.

Can you show your `package.json` ?

**Comment by acuntex** [comment]
Hi @tinesoft,
it's working perfectly but it's just an ugly warning ;-)

^2.0.0 matches 2.x.x which means that any major version bump will not match thus resulting in a warning.
You could try ">=" instead of "^" as peerdependecy.

Here is an example of another module: https://github.com/ngx-translate/core/blob/master/package.json

**Comment by tinesoft** [comment]
Hi @acuntex ,

Thanks for the tip, i have indeed misunderstood the meaning of '^' in dependency's version.
I will change that soon.

Cheers,
