### ISSUE TITLE
Cookie revoke button not hideable

### ISSUE THREAD

**Issue by Johnny99211** [tinesoft/ngx-cookieconsent#82]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

I've found out that when I set `revokable: false` to false and when I declined or accepted the police that the revoke button at the bottom left side is still there but I want to remove it completely when a decision was made. So something might be broken here?

### CookieConsent and Library Versions?
```
- cookieconsent version: 3.1.1
- ngx-cookieconsent version: 2.2.3
```

### OS Version?
> macOS(Catalina)

### Angular, Node and al Versions?

```
Angular CLI: 7.3.5
Node: 12.4.0
OS: darwin x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.5
@angular-devkit/core         7.3.5
@angular-devkit/schematics   7.3.5
@schematics/angular          7.3.5
@schematics/update           0.13.5
rxjs                         6.3.3
typescript                   3.2.4
```

### Repro steps
Setup the cookie consent with the following options and accept or decline the cookies:

```
const cookieConfig: NgcCookieConsentConfig = {
  cookie   : {
    domain: environment.cookieDomain
  },
  position : 'bottom-left',
  theme    : 'classic',
  palette  : {
    popup : {
      background: 'var(--secondary-color)',
      text      : '#ffffff',
      link      : '#ffffff'
    },
    button: {
      background: 'var(--main-color)',
      text      : '#ffffff',
      border    : 'transparent'
    }
  },
  revokable: false,
  type     : 'opt-in',
  content  : {
    message: 'Test',
    allow  : 'Accept',
    deny   : 'Decline',
    link   : 'Privacy',
    href   : '/privacy'
  }
};
```

### The log given by the failure
There is no stacktrace or errors given.

### Desired functionality
There should be no button at the left corner to open the cookie notice again.

**Comment by tinesoft** [comment]
Hi @Johnny99211 ,

This is a (feature?) of the underlying `cookieconsent` on top of which, this Angular module is written on.

I guess it is there in case the user changes his mind about revoking?

Anyway,  there is no much I can do.
Maybe ask on https://github.com/osano/cookieconsent/issues

Closing
