### ISSUE TITLE
Usage of i18nsupport AND custom-layout at the same time

### ISSUE THREAD

**Issue by vsohlen** [tinesoft/ngx-cookieconsent#85]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### CookieConsent and Library Versions?
```
- cookieconsent version: 3.1.1
- ngx-cookieconsent version: 2.2.3
```

### OS Version?

macOs - Catalina

### Angular, Node and al Versions?

Angular CLI: 9.1.1
Node: 12.16.1
Angular: 9.1.2

### Desired functionality

I need to use both the functionality for i18n - translations as well as a custom layout - but I really can't figure out how to solve this. This is since the site i'm building for need support for both swedish and english in this case and the ux-designers have made a mock that needs the usage of custom layout-functionality.

**Comment by tinesoft** [comment]
Hi @vsohlen 

Thanks for using the library.

Regarding your query, have you read [Custom Layout Support](https://github.com/tinesoft/ngx-cookieconsent#custom-layout-support) and [I18n Support](https://github.com/tinesoft/ngx-cookieconsent#i18n-support)? All the information are there, really.

If you still can't figure out how to achieve what you are looking for, maybe share with me this custom layout from your UX-designers, and i will try to assist you more.


cheers

**Comment by tinesoft** [comment]
closed due to inactivity
