### ISSUE TITLE
How to implement using only webpack builder and Angular 4

### ISSUE THREAD

**Issue by GetTaxSolutions** [tinesoft/ngx-cookieconsent#9]
Hello, 

I'm trying to implement this package using webpack only. My project is building using only this way to build. Can you give some instruction how to do it? I'm trying to add the scripts in _Layout or main app component but the result is:

> AppComponent_Host.html:1 ERROR TypeError: Cannot read property 'initialise' of undefined
>     at NgcCookieConsentService.init (cookieconsent.service.js:53)
>     at new NgcCookieConsentService (cookieconsent.service.js:23)
>     at _createClass (core.es5.js:9532)
>     at _createProviderInstance$1 (core.es5.js:9500)
>     at resolveNgModuleDep (core.es5.js:9485)
>     at NgModuleRef_.get (core.es5.js:10577)
>     at resolveDep (core.es5.js:11080)
>     at createClass (core.es5.js:10944)
>     at createDirectiveInstance (core.es5.js:10764)
>     at createViewNodes (core.es5.js:12212)  

Thank you,
Gettaxsolutions team

**Comment by tinesoft** [comment]
Hi,

I need more info about your setup, as it seems not to be a regular angular cli, nor SystemJS project...

You need to install both 'ngx-cookieconsent' and 'cookieconsent' package , and they must be referenced somehow in your main 'index.html'.

**Comment by GetTaxSolutions** [comment]
This is the base project configuration which I'm trying to add this component: 

> https://github.com/MarkPieszak/aspnetcore-angular2-universal

I added both packages. I can see the menu but have to copy manually both files in wwwroot/assets and point to this virtual path. But I don't like this solution. May be have better way to be done.

**Comment by tinesoft** [comment]
I had a look at the starter you mentioned.
Indeed you shouldn't copy any files manually in 'wwwroot' : this is the job of the build system.

I don't particularly know this starter well, but from what I can tell, after you installed the packages, you must referenced them in the `webpack.config.vendor.js` so that they're integrated in final bundles:

```
const treeShakableModules = [
    '@angular/animations',
    '@angular/common',
    '@angular/compiler',
    '@angular/core',
    '@angular/forms',
    '@angular/http',
    '@angular/platform-browser',
    '@angular/platform-browser-dynamic',
    '@angular/router',
    'ngx-bootstrap',
    'zone.js',
    'ngx-cookieconsent',
    'cookieconsent/build/cookieconsent.min.js'
];
const nonTreeShakableModules = [
    // 'bootstrap',
    // 'bootstrap/dist/css/bootstrap.css',
    'core-js',
    // 'es6-promise',
    // 'es6-shim',
    'event-source-polyfill',
    // 'jquery',
    'cookieconsent/build/cookieconsent.min.css'
];
```

**Comment by GetTaxSolutions** [comment]
This is a good advice. I added them and found solution with some changes in webpack.config
Thank you

**Comment by sandroverna** [comment]
> This is a good advice. I added them and found solution with some changes in webpack.config
> Thank you

hi GetTaxSolutions,
Is it possible to describe the solution found in this discussion?
so it can also be applied by others who have encountered the same problem.
thank you
